### ISSUE TITLE
Exception when Compiling in Dev Mode

### ISSUE THREAD

**Issue by DMT-EB** [EloBuddy/EloBuddy.Issues#36]
Compiling an addon ONLY in dev mode would throw an exception:

```
Exception: System.IO.IOException: The process cannot access the file 'C:\Users\XXX\AppData\Roaming\EloBuddy\Addons\DMT_Awareness_EE51EC5.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at EloBuddy.Loader.Data.ElobuddyAddon.Compile(Boolean refreshDisplay)
```

**Comment by stefsot** [comment]
unload the addons from the game (F6) before attempting to recompile them
