### ISSUE TITLE
I got message to report this, i dont know what it is ^^ after error i reloaded eb with f5 twice

### ISSUE THREAD

**Issue by Andrijano1** [EloBuddy/EloBuddy.Issues#64]
[EloBuddy] EloBuddy (15:48:54 - 01:49:59 Feb 26 2016) loading...
[EloBuddy] [!] OpenFileMapping error: 0x00000002
[EloBuddy] [!] Failed to load memory layout, falling back on paths.
Sandbox: Reload, getting configuration failed
System.TimeoutException: The open operation did not complete within the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout. ---> System.TimeoutException: The read from the pipe did not complete within the allotted timeout of 00:00:59.9964997. The time allotted to this operation may have been a portion of a longer timeout.
   at System.ServiceModel.Channels.PipeConnection.WaitForSyncRead(TimeSpan timeout, Boolean traceExceptionsAsErrors)
   at System.ServiceModel.Channels.PipeConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgrade(StreamUpgradeInitiator upgradeInitiator, IConnection& connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace:
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EloBuddy.Sandbox.Shared.ILoaderService.GetConfiguration(Int32 pid)
   at EloBuddy.Sandbox.SandboxConfig.Reload()
Sandbox: Reload, config is null
Sandbox: Reload, getting configuration failed
System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.IOException: The read operation failed, see inner exception. ---> System.ServiceModel.CommunicationException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d). ---> System.IO.PipeException: There was an error reading from the pipe: The pipe has been ended. (109, 0x6d).
   at System.ServiceModel.Channels.PipeConnection.FinishSyncRead(Boolean traceExceptionsAsErrors)
   at System.ServiceModel.Channels.PipeConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.PipeConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.NegotiateStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   --- End of inner exception stack trace ---
   at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.NegotiateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   --- End of inner exception stack trace ---

Server stack trace:
   at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]:
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at EloBuddy.Sandbox.Shared.ILoaderService.GetConfiguration(Int32 pid)
   at EloBuddy.Sandbox.SandboxConfig.Reload()
Sandbox: Reload, config is null
Sandbox: An exception occurred creating the AppDomain!
System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at EloBuddy.Sandbox.SandboxDomain.CreateDomain(String domainName)
Sandbox: AppDomain creation failed, please report this error!
Loading EloBuddy
Loading EloBuddy.SDK
Loading 11 Addons
[23:31:38 - Info] ----------------------------------
[23:31:38 - Info] Loading SDK Bootstrap
[23:31:38 - Info] ----------------------------------
[23:31:41 - Info] Loaded a total of 3 fonts:
[23:31:41 - Info]  -> Gill Sans MT Light
[23:31:41 - Info]  -> Gill Sans MT Pro Book
[23:31:41 - Info]  -> Gill Sans MT Pro Medium
[23:31:41 - Info] EntityManager.Heroes: Allies (5) Enemies (5)
[23:31:42 - Info] TargetSelector loaded.
[23:31:42 - Info] Orbwalker loaded.
[23:31:42 - Info] Prediction loaded.
[23:31:42 - Warn] 'Jhin' was not found in the DamageLibrary!
[23:31:42 - Info] DamageLibrary loaded.
[23:31:42 - Info] ----------------------------------
[23:31:42 - Info] SDK Bootstrap fully loaded!
[23:31:42 - Info] ----------------------------------
Loading EloBuddy
Loading EloBuddy.SDK
Loading 11 Addons
[23:33:05 - Info] ----------------------------------
[23:33:05 - Info] Loading SDK Bootstrap
[23:33:05 - Info] ----------------------------------
[23:33:08 - Info] Loaded a total of 3 fonts:
[23:33:08 - Info]  -> Gill Sans MT Light
[23:33:08 - Info]  -> Gill Sans MT Pro Book
[23:33:08 - Info]  -> Gill Sans MT Pro Medium
[23:33:08 - Info] EntityManager.Heroes: Allies (5) Enemies (5)
[23:33:09 - Info] TargetSelector loaded.
[23:33:16 - Info] Orbwalker loaded.
[23:33:16 - Info] Prediction loaded.
[23:33:16 - Warn] 'Jhin' was not found in the DamageLibrary!
[23:33:16 - Info] DamageLibrary loaded.
[23:33:16 - Info] ----------------------------------
[23:33:16 - Info] SDK Bootstrap fully loaded!
[23:33:16 - Info] ----------------------------------

**Comment by Andrijano1** [comment]
It happend in botting account with volibot, addons used are evadeplus, autobuddy and rice and checked addons was some champs addons like ashe, soraka, kogmaw, jhin...And autobuddy stopped working after that, and when i pressed shift in game nothing happens

**Comment by coman3** [comment]
@Hellsing Seems the Sandbox caused this?

**Comment by Hellsing** [comment]
Does this issue still exist?

**Comment by Andrijano1** [comment]
Really dont know , it happend only once , so maybe is doesnt, but who knows^^

**Comment by Hellsing** [comment]
k, closing this then, thanks anyways
