### ISSUE TITLE
SharpDX.Xinput Extension: IsConnected causing fatal error

### ISSUE THREAD

**Issue by ghost** [EloBuddy/EloBuddy.Issues#70]
[7:26:19 - Warn] Failed to notify OnLoadingComlete listener!
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> **System.Security.VerificationException: Operation could destabilize the runtime.**
   at SharpDX.XInput.XInput.XInputGetState(Int32 dwUserIndex, State& stateRef)
   at SharpDX.XInput.Controller.get_IsConnected()
   at GenesisController.Program.OnLoadingComplete(EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at EloBuddy.SDK.Events.Loading.CallLoadingComplete()

Code:
https://github.com/Alweul/EloBuddy/blob/ae1dfd293256294f37dae546a5b9b5f4c0b786f4/GenesisController/GenesisController/Program.cs#L21-L36

**Comment by Hellsing** [comment]
Will take care of that soon, it's because that XInput isn't fully trusted yet.

**Comment by ghost** [comment]
Soon™

**Comment by Hellsing** [comment]
Fixed
